AWSTemplateFormatVersion: '2010-09-09'
Description: Defines a private s3 bucket resource

Parameters:
  BucketName:
    Type: String
    Description: The name of the S3 bucket
  VersioningStatus:
    Type: String
    Default: Disabled
    AllowedValues:
      - Enabled
      - Suspended
      - Disabled
    Description: Specify the versioning status for the S3 bucket

Conditions:
  EnableVersioning: !Not
    - !Equals [ !Ref VersioningStatus, Disabled ]

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      AccessControl: Private
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration: !If
        - EnableVersioning
        - Status: !Ref VersioningStatus
        - !Ref AWS::NoValue

Outputs:
  BucketName:
    Value: !Ref Bucket