AWSTemplateFormatVersion: '2010-09-09'
Description: Defines a dynamodb table resource

Parameters:
  TableName:
    Type: String
    Description: The name of the DynamoDB table
  HashKeyName:
    Type: String
    Description: Name of the HASH (partition) key
  HashKeyType:
    Type: String
    AllowedValues:
      - S
      - 'N'
      - B
    Default: S
    Description: Type of the HASH key (S=String, N=Number, B=Binary)
  RangeKeyName:
    Type: String
    Default: ''
    Description: Name of the optional RANGE (sort) key
  RangeKeyType:
    Type: String
    AllowedValues:
      - S
      - 'N'
      - B
    Default: S
    Description: Same as HashKeyType, but for the RANGE key

Conditions:
  HasRangeKey: !Not
    - !Equals
      - !Ref RangeKeyName
      - ''

Resources:
  Table:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref TableName
      AttributeDefinitions:
        - AttributeName: !Ref HashKeyName
          AttributeType: !Ref HashKeyType
        - !If
          - HasRangeKey
          - AttributeName: !Ref RangeKeyName
            AttributeType: !Ref RangeKeyType
          - !Ref AWS::NoValue
      KeySchema:
        - AttributeName: !Ref HashKeyName
          KeyType: HASH
        - !If
          - HasRangeKey
          - AttributeName: !Ref RangeKeyName
            KeyType: RANGE
          - !Ref AWS::NoValue
      BillingMode: PAY_PER_REQUEST

Outputs:
  TableName:
    Value: !Ref Table