AWSTemplateFormatVersion: '2010-09-09'
Description: Defines a private s3 bucket resource

Parameters:
  BucketName:
    Type: String
    Description: The name of the S3 bucket
  VersioningStatus:
    Type: String
    Default: Disabled
    AllowedValues:
      - Enabled
      - Suspended
      - Disabled
    Description: Specify the versioning status for the S3 bucket

Conditions:
  BucketVersioning: !Not
    - !Equals
      - !Ref VersioningStatus
      - Disabled
  NoBucketVersioning: !Equals
    - !Ref VersioningStatus
    - Disabled
Resources:
  BucketUnversioned:
    Type: AWS::S3::Bucket
    Condition: NoBucketVersioning
    Properties:
      BucketName: !Ref BucketName
      AccessControl: Private
  BucketVersioned:
    Type: AWS::S3::Bucket
    Condition: BucketVersioning
    Properties:
      BucketName: !Ref BucketName
      AccessControl: Private
      VersioningConfiguration:
        Status: !Ref VersioningStatus

Outputs:
  BucketName:
    Value: !If
      - BucketVersioning
      - !Ref BucketVersioned
      - !Ref BucketUnversioned