AWSTemplateFormatVersion: '2010-09-09'
Description: Defines a service that runs on an ECS cluster, with a load balancer in front

Parameters:
  TaskDefinitionArn:
    Type: String
    Description: The Arn of the task definition
  RoutePatterns:
    Type: CommaDelimitedList
    Description: The pattern of routes
  ClusterName:
    Type: String
    Description: Name of the ECS cluster to deploy the service on
  LoadBalancerArn:
    Type: String
    Description: Arn of the load balancer to attach the service to
  ListenerArn:
    Type: String
    Description: Arn of the load balancer's Listener to attach the service to
  VpcId:
    Type: String
    Description: ID of the VPC to start the instances in

  HealthCheckPath:
    Type: String
    Description: The route on which GET requests are sent to check the health of the service
    Default: '/'

Resources:
  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub ${AWS::StackName}-TargetGroup
      VpcId: !Ref VpcId
      Port: 80
      Protocol: HTTP
      TargetType: instance
      HealthCheckProtocol: HTTP
      HealthCheckPort: traffic-port
      HealthCheckPath: !Ref HealthCheckPath
      HealthCheckIntervalSeconds: 60
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 5
      UnhealthyThresholdCount: 2
      Matcher:
        HttpCode: '200'
  ListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup
      Conditions:
        - Field: path-pattern
          Values: !Ref RoutePatterns
      ListenerArn: !Ref ListenerArn
      Priority: 1
  Service:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref ClusterName
      DesiredCount: 1
      TaskDefinition: !Ref TaskDefinitionArn
      LaunchType: EC2
      LoadBalancers:
        - ContainerName: TaskContainerName
          ContainerPort: 80
          TargetGroupArn: !Ref TargetGroup
  ECSLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /ecs/${AWS::StackName}
      RetentionInDays: 30


Outputs:
  ServiceArn:
    Value: !Ref Service