AWSTemplateFormatVersion: '2010-09-09'
Description: Defines a route53 hosted zone and an eventual ACM certificate

Parameters:
  DomainName:
    Type: String
    Description: 'Domaine name of the website (ex: domain-name.com)'
    AllowedPattern: ^[a-z0-9-]+\.[a-z]{2,}$
    ConstraintDescription: Must be a valid domaine name
  HostedZoneId:
    Type: String
    Description: ID of the hosted zone to attach the domain name to

Resources:
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Sub '*.${DomainName}'
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Sub '*.${DomainName}'
          HostedZoneId: !Ref HostedZoneId
      Tags:
        - Key: Name
          Value: !Sub ${DomainName}Certificate

Outputs:
  CertificateArn:
    Value: !Ref Certificate