AWSTemplateFormatVersion: '2010-09-09'
Description: Defines the route53 hosted zone (for a publicly owned domain name, or a private fictive one) and an ACM certificate

Parameters:
  DomainName:
    Type: String
    Description: 'Domaine name of the website (ex: domain-name.com)'
    AllowedPattern: ^[a-z0-9-]+\.[a-z]{2,}$
    ConstraintDescription: Must be a valid domaine name

  VPCId:
    Type: String
    Description: Leave empty for a public hosted zone, provide a VPC ID to associate to for a private hosted zone.
    Default: ''

Conditions:
  IsPublicZone: !Equals [!Ref VPCId, '']

Resources:
  HostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: !Ref DomainName
      VPCs: !If
        - IsPublicZone
        - !Ref AWS::NoValue
        - - VPCId: !Ref VPCId
            VPCRegion: !Ref AWS::Region
      HostedZoneTags:
        - Key: Name
          Value: !Sub ${DomainName}HostedZone
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Condition: IsPublicZone
    Properties:
      DomainName: !Sub '*.${DomainName}'
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Sub '*.${DomainName}'
          HostedZoneId: !Ref HostedZone
      Tags:
        - Key: Name
          Value: !Sub ${DomainName}Certificate

Outputs:
  CertificateArn:
    Value: !Ref Certificate
    Condition: IsPublicZone
  DomainName:
    Value: !Ref DomainName
  HostedZoneId:
    Value: !Ref HostedZone