Parameters:
  QueueName:
    Type: String
    Description: "Name of the queue"
  MessageRetentionInSeconds:
    Type: Number
    Description: How long the email events are retained in the SQS queue
    Default: 345600   # 4 days
    MinValue: 60      # 1 minute
    MaxValue: 1209600 # 14 days

Resources:
  SQSQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Ref QueueName
      MessageRetentionPeriod: !Ref MessageRetentionInSeconds
  SQSQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref SQSQueue
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: sns.amazonaws.com
            Action: sqs:SendMessage
            Resource: !GetAtt SQSQueue.Arn
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sqs:SendMessage
            Resource: !GetAtt SQSQueue.Arn

Outputs:
  SQSQueueUrl:
    Value: !Ref SQSQueue
  SQSQueueArn:
    Value: !GetAtt SQSQueue.Arn