AWSTemplateFormatVersion: '2010-09-09'
Description: Defines a Fargate ECS cluster, for running any docker images as tasks

Resources:
  TaskSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for runners
      VpcId: !ImportValue PublicVpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
  TasksCluster:
    Type: AWS::ECS::Cluster
  TaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: ECSExecutionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: MyTaskDefinition
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: '256'
      Memory: '512'
      RuntimePlatform:
        OperatingSystemFamily: LINUX
        CpuArchitecture: X86_64
      ExecutionRoleArn: !Ref TaskExecutionRole
      ContainerDefinitions:
        - Name: ContainerNameWillBeOverwritten
          Image: 123456789012.dkr.ecr.us-west-1.amazonaws.com/unexisting-overwritten-image:latest
          PortMappings:
            - ContainerPort: 80
              HostPort: 80
              Protocol: tcp
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref TasksLogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: ecs
  TasksLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /tasks-log-group
      RetentionInDays: 30

Outputs:
  TaskSecurityGroupId:
    Value: !Ref TaskSecurityGroup
  TasksClusterId:
    Value: !Ref TasksCluster
  TaskDefinitionId:
    Value: !Ref TaskDefinition