Parameters:
  RepositoryName:
    Type: String
    Description: ECR repository name

  TagsMutable:
    Type: String
    Description: Whether the image tags are allowed to be mutable or not
    AllowedValues:
      - IMMUTABLE
      - MUTABLE
    Default: IMMUTABLE


Resources:
  ECRRepository:
    Type: AWS::ECR::Repository
    Properties:
        RepositoryName: !Ref RepositoryName
        ImageTagMutability: IMMUTABLE
        ImageScanningConfiguration:
            scanOnPush: true

Outputs:
  RepositoryName:
    Value: !Ref ECRRepository