Parameters:
  RepositoryName:
    Type: String
    Description: ECR repository name

  TagsMutable:
    Type: String
    Description: Whether the image tags are allowed to be mutable or not
    AllowedValues:
      - IMMUTABLE
      - MUTABLE
    Default: IMMUTABLE
  IsPublic:
    Type: String
    Description: Whether the ECR repository should be public or private
    AllowedValues:
      - true
      - false
    Default: false
  AutoDeleteUntagged:
    Type: String
    Description: Whether to create a lifecycle rule to automaticaly delete
    AllowedValues:
      - 'true'
      - 'false'
    Default: 'true'

Conditions:
  IsPublicRepo: !Equals [!Ref IsPublic, 'true']
  DeleteUntaggedLifecycle: !Equals ['true', !Ref AutoDeleteUntagged]

Resources:
  ECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref RepositoryName
      ImageTagMutability: IMMUTABLE
      ImageScanningConfiguration:
          scanOnPush: true
      LifecyclePolicy: !If
        - DeleteUntaggedLifecycle
        - LifecyclePolicyText: !Sub |
            {
              "rules": [
                {
                  "rulePriority": 1,
                  "description": "Remove untagged images after 1 day",
                  "selection": {
                    "tagStatus": "untagged",
                    "countType": "sinceImagePushed",
                    "countUnit": "days",
                    "countNumber": 1
                  },
                  "action": {
                    "type": "expire"
                  }
                }
              ]
            }
        - !Ref AWS::NoValue

  PublicECRRepository:
    Type: AWS::ECR::PublicRepository
    Condition: IsPublicRepo
    Properties:
      RepositoryName: !Ref RepositoryName
      RepositoryCatalogData:
        Description: ''

Outputs:
  RepositoryName:
    Value: !Ref ECRRepository