AWSTemplateFormatVersion: '2010-09-09'
Description: Defines a service that runs on an ECS cluster, with a load balancer in front

Parameters:
  DockerImage:
    Type: String
    Description: The address of the Docker image to use (busybox, python:3.12, public.ecr.aws/lambda/python:3.12, 717279735548.dkr.ecr.eu-west-3.amazonaws.com/sleek-simulations/webapp, ...)

  CompatibilityRequirements:
    Type: CommaDelimitedList
    Description: The type of clusters that the task should be compatible with. Might restrain the core/memory/disk space values that are valid.
    Default: EC2,FARGATE
  CpuUnits:
    Type: String
    Description: CPU resources allocated to each docker container running the service (1024 CPU units = 1 cpu core)
    Default: '256'
  MemoryMiB:
    Type: String
    Description: Memory resources allocated to each docker container running the service (in MiB)
    Default: '512'
  DiskSpaceGiB:
    Type: String
    Description: Disk space in GiB
    Default: '20'
  EnvironmentVariables:
    Type: CommaDelimitedList
    Description: 'The environment variables to add to the worker nodes, as a JSON string. Example: !Sub ''[{"Name": "AWS_DEFAULT_REGION", "Value": "${AWS::Region}"}, {"Name": "AWS_STACK_NAME", "Value": "${AWS::StackName}"}]'''
    Default: '[]'
  RunerRolePolicyArn:
    Type: String
    Description: The Arn of an AWS::IAM::ManagedPolicy object that will be used to create the role EC2 endorses. Or an empty string for default rights.
    Default: ''

Conditions:
  NotHasPolicy: !Equals ['', !Ref RunerRolePolicyArn]

Mappings:
  PowersOfTwo:
    "256": { Value: 256 }
    "512": { Value: 512 }
    "1024": { Value: 1024 }
    "2048": { Value: 2048 }
    "4096": { Value: 4096 }
    "8192": { Value: 8192 }
    "16384": { Value: 16384 }
    "32768": { Value: 32768 }
    "65536": { Value: 65536 }
    "120000": { Value: 120000 }
  DiskSpaceValues:
    "20": { Value: 20 }
    "40": { Value: 40 }
    "60": { Value: 60 }
    "80": { Value: 80 }
    "100": { Value: 100 }
    "120": { Value: 120 }
    "140": { Value: 140 }
    "160": { Value: 160 }
    "180": { Value: 180 }
    "200": { Value: 200 }

Resources:
  ExecutionRole:  # this is the role of the instance that execute the docker image, not the role endorsed from the docker image
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${AWS::StackName}-ExecutionRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
  DefaultRunnerPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub ${AWS::StackName}-DefaultRunnerPolicy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
              - ecr:GetAuthorizationToken
              - ecr:BatchCheckLayerAvailability
              - ecr:GetDownloadUrlForLayer
              - ecr:BatchGetImage
            Resource: "*"
  RunnerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${AWS::StackName}-RunnerRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns: 
        - !Ref DefaultRunnerPolicy
        - !If
          - NotHasPolicy
          - !Ref AWS::NoValue
          - !Ref RunerRolePolicyArn
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub ${AWS::StackName}-TaskFamily
      ContainerDefinitions:
        - Name: TaskContainerName
          Image: !Ref DockerImage
          Environment: !Ref EnvironmentVariables
          Cpu: !FindInMap [PowersOfTwo, !Ref CpuUnits, Value]
          Memory: !FindInMap [PowersOfTwo, !Ref MemoryMiB, Value]
          Essential: true
          PortMappings:
            - ContainerPort: 80
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref ECSLogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: !Sub ${AWS::StackName}-Task
      EphemeralStorage:
        SizeInGiB: !FindInMap [DiskSpaceValues, !Ref DiskSpaceGiB, Value]
      RequiresCompatibilities: !Ref CompatibilityRequirements
      NetworkMode: host
      TaskRoleArn: !Ref RunnerRole
      ExecutionRoleArn: !Ref ExecutionRole
  ECSLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /ecs/${AWS::StackName}
      RetentionInDays: 30

Outputs:
  TaskDefinitionArn:
    Value: !Ref TaskDefinition